name: Rentzila Create Unit Photo Tab Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install


      - name: Set up environment variables
        run: |
          echo "VALID_EMAIL=${{ secrets.VALID_EMAIL}}" >> .env
          echo "VALID_PASSWORD=${{ secrets.VALID_PASSWORD}}" >> .env

      - name: Run tests
        run: npx playwright test tests/test.photo.tab.spec.ts --config=playwright.config.chrome.ts
