name: Rentzila Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install


      - name: Set up environment variables
        run: |
          echo "ADMIN_EMAIL=${{secrets.ADMIN_EMAIL}}" >> .env
          echo "ADMIN_PASSWORD=${{secrets.ADMIN_PASSWORD}}" >> .env
          echo "VALID_EMAIL=${{ secrets.VALID_EMAIL}}" >> .env
          echo "VALID_PASSWORD=${{ secrets.VALID_PASSWORD}}" >> .env
          echo "VALID_PHONE=${{ secrets.VALID_PHONE}}" >> .env
          echo "CORRECT_PHONE_NUMBERS_FULL=${{ secrets.CORRECT_PHONE_NUMBERS_FULL }}" >> .env
          echo "CORRECT_PHONE_NUMBERS_WITHOUT_PLUSL=${{ secrets.CORRECT_PHONE_NUMBERS_WITHOUT_PLUS }}" >> .env
          echo "CORRECT_PHONE_NUMBERS_WITHOUT_PLUS38L=${{ secrets.CORRECT_PHONE_NUMBERS_WITHOUT_PLUS38 }}" >> .env
          echo "HOMEPAGE_URL=${{ secrets.HOMEPAGE_URL }}" >> .env

      - name: Run tests
        run: npx playwright test tests/test.login.spec.ts --config=playwright.config.chrome.ts
      
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: test-results
